export interface MarkuplintAdapterSettings {
  /** If given explicitly, resolved from workspaceRoot. */
  configFile?: string;

  /** If configFile is not set, search upward from sourceFilename. */
  searchConfig?: boolean; // default: true

  /** Adjusts source-style rules that do not fit HTML generated by the bridge. */
  profile?: "generated-html" | "as-configured"; // default: generated-html

  /**
   * Per-rule overrides applied after the generated-html profile overlay.
   * Lets you re-enable a specific rule that the overlay disabled.
   */
  profileRuleOverrides?: Readonly<Record<string, boolean>>;

  locale?: string;
}
